language: python

notifications:
  email: false

branches:
  only:
  - master

python:
- '3.4'
- '3.5'
- '3.6'

before_install:
- which python
- python --version
- sudo apt-get update
- sudo apt-get install libgmp-dev libmpfr-dev

- git clone https://github.com/fredrik-johansson/flint2.git
- cd flint2
- ./configure
- make
- sudo make install
- cd ..

- git clone https://github.com/fredrik-johansson/arb.git
- cd arb
- ./configure
- make
- sudo make install
- cd ..

install:
- pip install mpmath
- pip install numpy
- pip install cython
- pip install pytest pytest-cov
- pip freeze
- python setup.py build
- python setup.py install

script:
- py.test tests/ -v --cov=progression --cov-report term-missing


after_success:
- bash <(curl -s https://codecov.io/bash)
